site_name: mpy.Dot.Dev
site_url: https://mpy.dev
repo_url: https://github.com/mpyeager
site_description: 'mpyDotDev development site'
site_author: 'Matthew Yeager'
nav:
  - Home: index.md
  - L010: level010.md
  - L020: level020.md
  - L030: level030.md
  - L040: level040.md
  - L050: level050.md
  - L060: level060.md
  - L070: level070.md
  - L080: level080.md
  - L090: level090.md
  - L100: level100.md
  - L110: level110.md
  - L120: level120.md
  - L130: level130.md
theme:
  name: bootstrap386
  locale: en
extra:
  version: 1.0
